### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by miki-tebe** [miquelruiz/yrs#2]
i'm on windows and tried installing by following the readme instruction and got the following error. I couldn't figure out what the error was; go noob here. Thanks in advance 
![image](https://user-images.githubusercontent.com/26773624/219974443-bb6c1e8d-972e-4e95-ae9d-c723ffc26da4.png)

**Comment by miquelruiz** [comment]
Yeah, those installation instructions are pretty outdated. Let me fix a few things so the CLI can get installed again.

Be warned, though: I haven't even tried to run it on windows, so I'm not sure if it's going work (I'll accept PR's in that direction as long as they don't break current linux functionality).

If you want to try the (very rough 'cause I'm no web designer) web interface, the easiest is to give the docker container a go: https://hub.docker.com/r/miquelruiz/yrs

**Comment by miquelruiz** [comment]
Last commit should have fixed the installation issue. README should reflect the right command now:
```
go install github.com/miquelruiz/yrs/cmd/yrs@latest
```

If you get this error:
```
go: github.com/miquelruiz/yrs/cmd/yrs@latest: module github.com/miquelruiz/yrs@latest found (v0.0.0-20230219033517-695cb77b4020), but does not contain package github.com/miquelruiz/yrs/cmd/yrs
```
It's because there's a broken version cached by the go module mirror. Try setting the GOPROXY env variable to "direct" (I've no idea how to do such thing on windows).

**Comment by miki-tebe** [comment]
Thanks for the quick response, will looking into the docker setup looks promising. While trying the command line installation I got this error not sure if its related with the previous issue.

![image](https://user-images.githubusercontent.com/26773624/220057495-4e160d4d-7c8b-4cf8-9fff-8989dc156699.png)

**Comment by miquelruiz** [comment]
I'm afraid you'll have to do some legwork to get it running on windows: https://github.com/mattn/go-sqlite3#windows

I'll close the issue since that doesn't seem to be related with this module specifically.

**Comment by miki-tebe** [comment]
Thanks for the help 🙇. The docker setup works.
